{% set name = "cmeutils" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/cmeutils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9ea078f8e99aaa16d7ca7c83d82a728f1315863dc40d595e2cef94239c7ba03d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0 

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - freud >=3.0
    - gmso >=0.11.2
    - fresnel >=0.13.5
    - gsd >=3.0
    - hoomd >=4.0
    - mbuild >=0.17.0
    - numpy
    - pip
    - python >=3.10
    - matplotlib
    - pymbar >=4.0
    - rowan

test:
  imports:
    - cmeutils
  requires:
    - pip

about:
  home: https://github.com/cmelab/cmeutils
  summary: 'Useful functions by and for the CME lab.'
  description: |
    Helpful functions used by the CME Lab.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/cmelab/cmeutils
  dev_url: https://github.com/cmelab/cmeutils

extra:
  recipe-maintainers:
    - jennyfothergill
    - chrisjonesBSU
    - marjanalbooyeh
