{% set name = "cmeutils" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/cmeutils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 73865096caf65fc315b16a0aadea35185cd0d88e10302c1257e5c274c4c03f24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - freud >=2.13.1
    - fresnel >=0.13.5
    - gsd >=3.0
    - hoomd >=4.0
    - mbuild >=0.16.4
    - numpy
    - pip
    - matplotlib
    - pymbar >=4.0
    - rowan

test:
  imports:
    - cmeutils
  requires:
    - pip

about:
  home: https://github.com/cmelab/cmeutils
  summary: 'Useful functions by and for the CME lab.'
  description: |
    Helpful functions used by the CME Lab.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/cmelab/cmeutils
  dev_url: https://github.com/cmelab/cmeutils

extra:
  recipe-maintainers:
    - jennyfothergill
    - chrisjonesBSU
    - marjanAlbouye
