{% set name = "cmeutils" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/cmeutils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e17a77aa8a936b6455532542d28d711e7627a32073dcb5c50366befb27fbcaa9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - freud >=2.13.1
    - gmso >=0.11.2
    - fresnel >=0.13.5
    - gsd >=3.0
    - hoomd >=4.0
    - mbuild >=0.16.4
    - numpy
    - pip
    - matplotlib
    - pymbar >=4.0
    - rowan

test:
  imports:
    - cmeutils
  requires:
    - pip

about:
  home: https://github.com/cmelab/cmeutils
  summary: 'Useful functions by and for the CME lab.'
  description: |
    Helpful functions used by the CME Lab.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/cmelab/cmeutils
  dev_url: https://github.com/cmelab/cmeutils

extra:
  recipe-maintainers:
    - jennyfothergill
    - chrisjonesBSU
    - marjanAlbouye
