{% set name = "cmeutils" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/cmeutils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd5048a292fe72fcdfcf8cfb256b3e07f794989d6f059d2545ea041b37ae1c53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python =3.9
    - pip
  run:
    - python =3.9
    - fresnel
    - freud >=2.13.1
    - gsd >=3.0
    - hoomd <4.0=*cpu*
    - mbuild
    - numpy
    - pip
    - matplotlib
    - pymbar >=4.0
    - rowan

test:
  imports:
    - cmeutils
  requires:
    - pip

about:
  home: https://github.com/cmelab/cmeutils
  summary: 'Useful functions by and for the CME lab.'
  description: |
    Helpful functions used by the CME Lab.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/cmelab/cmeutils
  dev_url: https://github.com/cmelab/cmeutils

extra:
  recipe-maintainers:
    - jennyfothergill
    - chrisjonesBSU
    - marjanAlbouye
